openapi: 3.0.3
info:
  title: Application Event
  description: |-
    This is a Application event server.
  contact:
    name: Github repository
    url: https://github.com/sergeybabykin/Application-event
  license:
    name: MIT License
    url: "https://github.com/sergeybabykin/Application-event/blob/main/LICENSE"
  version: 0.1.0
servers:
  - url: "https://application-event.onrender.com/api/"
tags:
  - name: get requests
    description: getting information from tables
  - name: create data requests
    description: getting information from tables
paths:
  /event_list:
    get:
      tags:
        - get requests
      summary: get list of events
      responses:
        '200':
          description: Successful get data
          content:
            application/json:
              schema:
                type: object
                properties:
                  events:
                    type: array
                    items:
                      $ref: '#/components/schemas/EventList'
        '404':
          description: No events found
    post:
      tags:
        - create data requests
      summary: create new event
      requestBody:
        description: Create a new pet in the store
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  format: int64
                calendar_id:
                  type: integer
                  format: int64
                event_type_id:
                  type: integer
                  format: int64
                c_start_date:
                  type: string
                  format: date
                c_end_date:
                  type: string
                  format: date
                group_id:
                  type: integer
                  format: int64
                student_id:
                  type: integer
                  format: int64
                staff_id:
                  type: integer
                  format: int64
      responses:
        '201':
          description: Event created
        '400':
          description: "Missing arguments"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Missing argument: {arg}"
  /event_type:
    get:
      tags:
        - get requests
      summary: get list of event types
      responses:
        '200':
          description: Successful get data
          content:
            application/json:
              schema:
                type: object
                properties:
                  event_types:
                    type: array
                    items:
                      $ref: '#/components/schemas/EventType'
        '404':
          description: No events found
  /groups:
    get:
      tags:
        - get requests
      summary: get list of groups
      responses:
        '200':
          description: Successful get data
          content:
            application/json:
              schema:
                type: object
                properties:
                  groupes:
                    type: array
                    items:
                      $ref: '#/components/schemas/Groups'
        '404':
          description: No groupes found
  /staff_list:
    get:
      tags:
        - get requests
      summary: get list of staff
      responses:
        '200':
          description: Successful get data
          content:
            application/json:
              schema:
                type: object
                properties:
                  groupes:
                    type: array
                    items:
                      $ref: '#/components/schemas/Staff'
        '404':
          description: No staff found
  /student:
    get:
      tags:
        - get requests
      summary: get list of student
      responses:
        '200':
          description: Successfull get data
          content:
            application/json:
              schema:
                type: object
                properties:
                  students:
                    type: array
                    items:
                      $ref: '#/components/schemas/Student'
        '404':
          description: No students found
  /student_board:
    get:
      tags:
        - get requests
      summary: get list of student
      responses:
        '200':
          description: Successfull get data
          content:
            application/json:
              schema:
                type: object
                properties:
                  board:
                    type: array
                    items:
                      $ref: '#/components/schemas/StudentBoard'
        '404':
          description: No student board

components:
  schemas:
    EventList:
      type: object
      properties:
        el_id:
          type: integer
          format: int64
          example: 1
        el_calendar_id :
          type: integer
          format: int64
          example: 1
        el_event_type_id:
          type: integer
          format: int64
          example: 1
        el_c_start_date:
          type: string
          format: date
          example: 2019-09-10 15:00:00
        el_c_end_date:
          type: string
          format: date
          example: 2019-09-10 18:00:00
        el_group_id:
          type: integer
          format: int64
          example: 1
        el_student_id:
          type: integer
          format: int64
          example: 1
        el_staff_id:
          type: integer
          format: int64
          example: 1
    EventType:
      type: object
      properties:
        et_id:
          type: integer
          format: int64
          example: 1
        et_name:
          type: string
          example: "День Знаний (1 сентября)"
        et_location:
          type: string
          example: "МУИВ"
        et_calendar_id:
          type: integer
          format: int64
          example: 1
    Groupes:
      type: object
      properties:
        gl_id:
          type: integer
          format: int64
          example: 1
        gl_name:
          type: string
          example: "ГРУППА_1"
        gl_year:
          type: string
          format: date
          example: "2019-09-01 10:00:00"
    Staff:
      type: object
      properties:
        sl_id:
          type: integer
          format: int64
          example: 1
        sl_firstname:
          type: string
          example: "Николай"
        sl_surname:
          type: string
          example: "Владимирович"
        sl_lastname:
          type: string
          example: "Величко"
        sl_division_id:
          type: integer
          format: int64
          example: 0
        sl_is_works:
          type: string
          enum:
            - "работает"
            - "не работает"
    Student:
      type: object
      properties:
        s_id:
          type: integer
          format: int64
          example: 1
        s_firstname:
          type: string
          example: "Елена"
        s_surname:
          type: string
          example: "Владимировна"
        s_lastname:
          type: string
          example: "Акиньшина"
        s_group_id:
          type: integer
          format: int64
          example: 1
        s_study_id:
          type: integer
          format: int64
          example: 1
    StudentBoard:
      type: object
      properties:
        sb_board_id:
          type: integer
          format: int64
          example: 1
        sb_calendar_id:
          type: integer
          format: int64
          example: 1
        sb_student_id:
          type: integer
          format: int64
          example: 1
        sb_position_id:
          type: integer
          format: int64
          example: 1
