openapi: 3.0.3
info:
  title: Application Event
  description: |-
    This is a Application event server.
  contact:
    name: Github repository
    url: https://github.com/exp-of-betrayal/Application-event
  license:
    name: MIT License
    url: https://github.com/exp-of-betrayal/Application-event/blob/main/LICENSE
  version: 0.1.0
servers:
  - url: "https://application-event.onrender.com/api/"
tags:
  - name: get requests
    description: getting information from table
paths:
  /event_list:
    get:
      tags:
        - pet
      summary: get list of events
      responses:
        '200':
          description: Successful get data
          content:
            application/json:
              schema:
                type: object
                properties:
                  events:
                    type: array
                    items:
                      $ref: '#/components/schemas/EventList'
        '404':
          description: No events found
  /event_type:
    get:
      tags:
        - pet
      summary: get list of event types
      responses:
        '200':
          description: Successful get data
          content:
            application/json:
              schema:
                type: object
                properties:
                  event_types:
                    type: array
                    items:
                      $ref: '#/components/schemas/EventType'
        '404':
          description: No events found
  /groupes:
    get:
      tags:
        - pet
      summary: get list of groupes
      responses:
        '200':
          description: Successful get data
          content:
            application/json:
              schema:
                type: object
                properties:
                  groupes:
                    type: array
                    items:
                      $ref: '#/components/schemas/Groupes'
        '404':
          description: No groupes found
  /staff_list:
    get:
      tags:
        - pet
      summary: get list of staff
      responses:
        '200':
          description: Successful get data
          content:
            application/json:
              schema:
                type: object
                properties:
                  groupes:
                    type: array
                    items:
                      $ref: '#/components/schemas/Staff'
        '404':
          description: No staff found
            
components:
  schemas:
    EventList:
      type: object
      properties:
        el_id:
          type: integer
          format: int64
          example: 1
        el_calendar_id :
          type: integer
          format: int64
          example: 1
        el_event_type_id:
          type: integer
          format: int64
          example: 1
        el_c_start_date:
          type: string
          format: date
          example: 2019-09-10 15:00:00
        el_c_end_date:
          type: string
          format: date
          example: 2019-09-10 18:00:00
        el_group_id:
          type: integer
          format: int64
          example: 1
        el_student_id:
          type: integer
          format: int64
          example: 1
        el_staff_id:
          type: integer
          format: int64
          example: 1
    EventType:
      type: object
      properties:
        et_id:
          type: integer
          format: int64
          example: 1
        et_name:
          type: string
          example: "День Знаний (1 сентября)"
        et_location:
          type: string
          example: "МУИВ"
        et_calendar_id:
          type: integer
          format: int64
          example: 1
    Groupes:
      type: object
      properties:
        gl_id:
          type: integer
          format: int64
          example: 1
        gl_name:
          type: string
          example: "ГРУППА_1"
        gl_year:
          type: string
          format: date
          example: "2019-09-01 10:00:00"
    Staff:
      type: object
      properties:
        sl_id:
          type: integer
          format: int64
          example: 1
        sl_firstname:
          type: string
          example: "Николай"
        sl_surname:
          type: string
          example: "Владимирович"
        sl_lastname:
          type: string
          example: "Величко"
        sl_division_id:
          type: integer
          format: int64
          example: 0
        sl_is_works:
          type: string
          enum:
            - "работает"
            - "не работает"
